In [30]:
import pandas as pd
import numpy as np

In [40]:
df_8 = pd.read_excel("8А_2023_2024.xlsx", header=8)
df_8.head()

,№,Unnamed: 1,Алг.,Биол.,Геогр.,Геом.,ГД,Англ.яз,Инф.,Ист.,...,ОБЖ,Разг о важном,Россия - мои горизонты,Рус.яз.,Смысл. чтен.,Техно 1 гр,Техно 2 гр,Физика,Физ-ра,Химия
0,п/п,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ученик 1,1 Четверть,3.0,4.0,5.0,3.0,3.0,4.0,5.0,5.0,...,5.0,NaN,NaN,3.0,3.0,4.0,NaN,3.0,5.0,3.0
2,NaN,2 Четверть,3.0,4.0,4.0,3.0,4.0,4.0,5.0,4.0,...,4.0,NaN,NaN,3.0,3.0,4.0,NaN,4.0,4.0,4.0
3,NaN,3 Четверть,3.0,4.0,4.0,3.0,4.0,4.0,5.0,5.0,...,4.0,NaN,NaN,4.0,4.0,5.0,NaN,3.0,5.0,4.0
4,NaN,4 Четверть,3.0,4.0,4.0,3.0,3.0,4.0,5.0,4.0,...,5.0,NaN,NaN,3.0,4.0,5.0,NaN,3.0,4.0,4.0

In [42]:
def clean_df(df, eight_class = True):
    tech_columns = ['Техно 1 гр', 'Техно 2 гр']
    if eight_class:
        df['Техно'] = df[tech_columns[0]].combine_first(df[tech_columns[1]])
    
    columns_to_drop = [
        *tech_columns,
        'Разг о важном', 
        'Россия -  мои горизонты'
    ]
    df = df.drop(columns=columns_to_drop, errors='ignore')
    
    df = df.drop(df.index[:1])
    df = df[df.iloc[:, 1] != "Итог. оценка"]
    
    df = df.rename(columns={'Unnamed: 1': 'Период'})

    if not eight_class:
        df['труд'] = df['труд'].fillna(method='ffill')
    
    return df.reset_index(drop=True)
    
df_8 = clean_df(df_8)

In [44]:
df_8.head(10)

,№,Период,Алг.,Биол.,Геогр.,Геом.,ГД,Англ.яз,Инф.,Ист.,Лит-ра,Муз.,Обществ.,ОБЖ,Рус.яз.,Смысл. чтен.,Физика,Физ-ра,Химия,Техно
0,Ученик 1,1 Четверть,3.0,4.0,5.0,3.0,3.0,4.0,5.0,5.0,3.0,4.0,5.0,5.0,3.0,3.0,3.0,5.0,3.0,4.0
1,NaN,2 Четверть,3.0,4.0,4.0,3.0,4.0,4.0,5.0,4.0,3.0,5.0,5.0,4.0,3.0,3.0,4.0,4.0,4.0,4.0
2,NaN,3 Четверть,3.0,4.0,4.0,3.0,4.0,4.0,5.0,5.0,4.0,4.0,5.0,4.0,4.0,4.0,3.0,5.0,4.0,5.0
3,NaN,4 Четверть,3.0,4.0,4.0,3.0,3.0,4.0,5.0,4.0,4.0,5.0,5.0,5.0,3.0,4.0,3.0,4.0,4.0,5.0
4,NaN,Год. оценка,3.0,4.0,4.0,3.0,4.0,4.0,5.0,5.0,4.0,5.0,5.0,5.0,3.0,4.0,3.0,5.0,4.0,5.0
5,Ученик 2,1 Четверть,3.0,4.0,3.0,3.0,3.0,3.0,5.0,4.0,3.0,3.0,4.0,4.0,3.0,3.0,3.0,4.0,3.0,3.0
6,NaN,2 Четверть,3.0,4.0,3.0,3.0,3.0,3.0,5.0,5.0,3.0,4.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0
7,NaN,3 Четверть,3.0,4.0,3.0,3.0,3.0,3.0,5.0,4.0,3.0,5.0,4.0,4.0,3.0,3.0,3.0,4.0,3.0,3.0
8,NaN,4 Четверть,3.0,4.0,3.0,3.0,3.0,3.0,4.0,4.0,3.0,3.0,4.0,4.0,3.0,3.0,3.0,4.0,3.0,4.0
9,NaN,Год. оценка,3.0,4.0,3.0,3.0,3.0,3.0,5.0,4.0,3.0,4.0,4.0,4.0,3.0,3.0,3.0,4.0,3.0,3.0

In [179]:
df_9 = pd.read_excel("9А_2024_2025.xlsx", header=8)
df_9 = clean_df(df_9, False)

C:\Users\motve\AppData\Local\Temp\ipykernel_21948\2765287323.py:20: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['труд'] = df['труд'].fillna(method='ffill')

In [183]:
df_9

,Период,Алг.,Биол.,Вер и Стат,Геогр.,Геом.,Англ.яз,Инф.,Ист.,Лит-ра,Обществ.,ОБиЗР,Рус.яз.,Смысл. чтен.,труд,Физика,Физ-ра,Химия
0,1 Четверть,3.0,3.0,3.0,4.0,3.0,4.0,5.0,4.0,3.0,4.0,5.0,3.0,3.0,5.0,3.0,5.0,4.0
1,2 Четверть,3.0,4.0,3.0,4.0,3.0,4.0,4.0,4.0,3.0,4.0,5.0,3.0,3.0,4.0,3.0,4.0,3.0
2,3 Четверть,3.0,3.0,3.0,4.0,3.0,0.0,5.0,4.0,3.0,4.0,5.0,4.0,4.0,4.0,3.0,5.0,4.0
3,1 Четверть,3.0,3.0,4.0,4.0,3.0,3.0,4.0,3.0,3.0,3.0,4.0,3.0,3.0,4.0,3.0,3.0,3.0
4,2 Четверть,3.0,3.0,3.0,4.0,3.0,3.0,4.0,3.0,3.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2 Четверть,4.0,4.0,3.0,5.0,4.0,5.0,4.0,4.0,4.0,3.0,5.0,4.0,5.0,5.0,4.0,5.0,4.0
71,3 Четверть,3.0,4.0,3.0,4.0,3.0,0.0,5.0,4.0,4.0,4.0,5.0,4.0,4.0,5.0,4.0,4.0,4.0
72,1 Четверть,4.0,4.0,3.0,5.0,3.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,3.0,5.0,4.0,4.0,5.0
73,2 Четверть,4.0,4.0,3.0,4.0,3.0,5.0,5.0,4.0,4.0,4.0,5.0,4.0,5.0,5.0,4.0,4.0,4.0
74,3 Четверть,3.0,4.0,4.0,5.0,4.0,0.0,5.0,4.0,5.0,4.0,5.0,4.0,5.0,5.0,3.0,4.0,4.0

In [189]:
df1 = df_8.copy()
df2 = df_9.copy()

In [191]:
df2 = df2.rename(columns={
    'Вер и Стат': 'ГД',
    'ОБиЗР': 'ОБЖ',
    'труд': 'Техно'
})

for col in df1.columns:
    if col not in df2.columns:
        df2[col] = None  # или pd.NA

for col in df2.columns:
    if col not in df1.columns:
        df1[col] = None  # или pd.NA

combined_df = pd.concat([df1, df2], ignore_index=True)

common_columns = sorted(set(df1.columns) | set(df2.columns))
combined_df = combined_df[common_columns]

combined_df['Муз.'] = combined_df['Муз.'].fillna('Нет данных')

C:\Users\motve\AppData\Local\Temp\ipykernel_21948\433726507.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([df1, df2], ignore_index=True)

In [199]:
combined_df.head(20)

,Алг.,Англ.яз,Биол.,ГД,Геогр.,Геом.,Инф.,Ист.,Лит-ра,Муз.,ОБЖ,Обществ.,Период,Рус.яз.,Смысл. чтен.,Техно,Физ-ра,Физика,Химия
0,3.0,4.0,4.0,3.0,5.0,3.0,5.0,5.0,3.0,4.0,5.0,5.0,1 Четверть,3.0,3.0,4.0,5.0,3.0,3.0
1,3.0,4.0,4.0,4.0,4.0,3.0,5.0,4.0,3.0,5.0,4.0,5.0,2 Четверть,3.0,3.0,4.0,4.0,4.0,4.0
2,3.0,4.0,4.0,4.0,4.0,3.0,5.0,5.0,4.0,4.0,4.0,5.0,3 Четверть,4.0,4.0,5.0,5.0,3.0,4.0
3,3.0,4.0,4.0,3.0,4.0,3.0,5.0,4.0,4.0,5.0,5.0,5.0,4 Четверть,3.0,4.0,5.0,4.0,3.0,4.0
4,3.0,4.0,4.0,4.0,4.0,3.0,5.0,5.0,4.0,5.0,5.0,5.0,Год. оценка,3.0,4.0,5.0,5.0,3.0,4.0
5,3.0,3.0,4.0,3.0,3.0,3.0,5.0,4.0,3.0,3.0,4.0,4.0,1 Четверть,3.0,3.0,3.0,4.0,3.0,3.0
6,3.0,3.0,4.0,3.0,3.0,3.0,5.0,5.0,3.0,4.0,4.0,4.0,2 Четверть,3.0,3.0,3.0,3.0,3.0,3.0
7,3.0,3.0,4.0,3.0,3.0,3.0,5.0,4.0,3.0,5.0,4.0,4.0,3 Четверть,3.0,3.0,3.0,4.0,3.0,3.0
8,3.0,3.0,4.0,3.0,3.0,3.0,4.0,4.0,3.0,3.0,4.0,4.0,4 Четверть,3.0,3.0,4.0,4.0,3.0,3.0
9,3.0,3.0,4.0,3.0,3.0,3.0,5.0,4.0,3.0,4.0,4.0,4.0,Год. оценка,3.0,3.0,3.0,4.0,3.0,3.0
10,2.0,3.0,3.0,4.0,4.0,3.0,5.0,4.0,4.0,4.0,4.0,4.0,1 Четверть,3.0,3.0,3.0,5.0,3.0,4.0
11,2.0,3.0,4.0,3.0,3.0,3.0,5.0,4.0,4.0,4.0,4.0,4.0,2 Четверть,3.0,4.0,3.0,4.0,3.0,3.0
12,3.0,3.0,3.0,4.0,3.0,3.0,5.0,4.0,3.0,5.0,4.0,4.0,3 Четверть,3.0,3.0,4.0,4.0,3.0,4.0
13,2.0,3.0,3.0,4.0,4.0,3.0,5.0,4.0,4.0,4.0,0.0,4.0,4 Четверть,3.0,3.0,5.0,4.0,NaN,3.0
14,2.0,3.0,3.0,4.0,4.0,3.0,5.0,4.0,4.0,4.0,4.0,4.0,Год. оценка,3.0,3.0,4.0,4.0,3.0,4.0
15,3.0,3.0,3.0,3.0,3.0,3.0,5.0,3.0,3.0,4.0,4.0,3.0,1 Четверть,3.0,3.0,3.0,4.0,3.0,3.0
16,3.0,3.0,4.0,3.0,3.0,3.0,5.0,3.0,3.0,5.0,4.0,3.0,2 Четверть,3.0,3.0,3.0,3.0,3.0,4.0
17,3.0,3.0,3.0,3.0,3.0,3.0,5.0,3.0,3.0,3.0,4.0,4.0,3 Четверть,3.0,3.0,3.0,5.0,3.0,3.0
18,3.0,3.0,4.0,3.0,3.0,3.0,4.0,3.0,4.0,4.0,4.0,3.0,4 Четверть,3.0,3.0,4.0,4.0,3.0,3.0
19,3.0,3.0,4.0,3.0,3.0,3.0,5.0,3.0,3.0,4.0,4.0,3.0,Год. оценка,3.0,3.0,3.0,4.0,3.0,3.0

In [201]:
new_order = [
    'Период', 'Алг.', 'Биол.', 'Геогр.', 'Геом.', 'ГД', 
    'Англ.яз', 'Инф.', 'Ист.', 'Лит-ра', 'Муз.', 
    'Обществ.', 'ОБЖ', 'Рус.яз.', 'Смысл. чтен.', 
    'Физика', 'Физ-ра', 'Химия', 'Техно'
]
combined_df = combined_df[new_order]

In [207]:
combined_df = combined_df.drop(columns=['Муз.'])

In [211]:
combined_df.to_csv("8-9 успеваемость.csv", index=False, encoding="utf-8-sig")