In [97]:
import pandas as pd
import numpy as np

In [140]:
df = pd.read_csv('успеваемость.csv')
df.head(10)

,ID,Класс,Период,Алг и матанализ,Биол.,Вер и Стат,Геогр.,Геом.,Англ.яз,Инф.,...,Обществ.,ОБиЗР,Практ. по матем.,Практ. по обществ.,Рус.яз.,Совр. литерат,Физика,Физ-ра,Фин.гр.,Химия
0,1,10.0,1 Полугодие,4.0,4.0,4.0,5.0,4.00,5.0,NaN,...,4.00,5.0,NaN,5.0,4.0,5.0,4.0,5.0,NaN,4.00
1,1,10.0,2 Полугодие,4.0,4.0,5.0,5.0,3.00,5.0,NaN,...,4.00,5.0,NaN,5.0,4.0,5.0,4.0,4.0,NaN,4.00
2,1,10.0,Год,4.0,4.0,5.0,5.0,4.00,5.0,NaN,...,4.00,5.0,NaN,5.0,4.0,5.0,4.0,5.0,NaN,4.00
3,1,11.0,1 Полугодие,4.0,4.0,4.0,5.0,4.00,5.0,5.0,...,5.00,5.0,NaN,NaN,4.0,5.0,4.0,5.0,NaN,5.00
4,1,11.0,2 Полугодие,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN
5,1,11.0,Год,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1,NaN,Средняя оценка,4.0,4.0,4.5,5.0,3.75,5.0,5.0,...,4.25,5.0,0.0,5.0,4.0,5.0,4.0,4.8,0.0,4.25
7,1,NaN,Итог. оценка,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2,10.0,1 Полугодие,5.0,5.0,5.0,5.0,5.00,5.0,NaN,...,5.00,5.0,NaN,5.0,5.0,5.0,5.0,5.0,NaN,5.00
9,2,10.0,2 Полугодие,5.0,5.0,5.0,5.0,5.00,5.0,NaN,...,5.00,5.0,NaN,5.0,5.0,5.0,5.0,5.0,NaN,5.00